spring:
  application:
    name: generate-report-service
  datasource:
    url: jdbc:mysql://localhost:3306/ctsproject
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8002