spring:
     application:
           name: customer-preference-service

     datasource:
           url: jdbc:mysql://localhost:3306/cognizant
           username: root
           password: root

     jpa:
           show-sql: true	
           hibernate:
              ddl-auto: update

server:
     port: 8001